"""initial schema

Revision ID: 48ae57c8e123
Revises: 
Create Date: 2026-08-09 14:18:21.214394

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ae57c8e123'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('cat_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('DETECTION', 'ALERT', name='activitykind', native_enum=False), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_camera_id'), 'activities', ['camera_id'], unique=False)
    op.create_index(op.f('ix_activities_cat_id'), 'activities', ['cat_id'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_kind'), 'activities', ['kind'], unique=False)
    op.create_table('cats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'track_id', name='uq_cats_camera_id_track_id')
    )
    op.create_index(op.f('ix_cats_camera_id'), 'cats', ['camera_id'], unique=False)
    op.create_index(op.f('ix_cats_track_id'), 'cats', ['track_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'name', name='uq_zones_camera_id_name')
    )
    op.create_index(op.f('ix_zones_camera_id'), 'zones', ['camera_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cat_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='alertstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_cat_id'), 'alerts', ['cat_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cat_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=False),
    sa.Column('in_danger_zone', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_detections_cat_id'), 'detections', ['cat_id'], unique=False)
    op.create_index(op.f('ix_detections_in_danger_zone'), 'detections', ['in_danger_zone'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index(op.f('ix_detections_in_danger_zone'), table_name='detections')
    op.drop_index(op.f('ix_detections_cat_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cat_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_camera_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_cats_track_id'), table_name='cats')
    op.drop_index(op.f('ix_cats_camera_id'), table_name='cats')
    op.drop_table('cats')
    op.drop_index(op.f('ix_activities_kind'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_cat_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_camera_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
